#!/bin/sh
#
# Author: Mark Felder <feld@FreeBSD.org>

# PROVIDE: nzbget
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable nzbget:
# nzbget_enable="YES"

. /etc/rc.subr

name="nzbget"
rcvar=nzbget_enable

load_rc_config $name

: ${nzbget_enable="NO"}
: ${nzbget_user:="nzbget"}
: ${nzbget_data_dir:="/usr/local/nzbget"}
: ${nzbget_exec_dir:="/usr/local/share/nzbget/bin"}

pidfile="${nzbget_data_dir}/nzbget.pid"

command=/usr/local/nzbget/nzbget
command_args="-D -c /usr/local/nzbget/config/nzbget.conf"

start_precmd="${name}_precmd"
start_cmd="${name}_start"
stop_cmd="${name}_stop"


nzbget_precmd()
{
        install -d -o ${nzbget_user} -m 755 /var/run/${name}
}

nzbget_start()
{
    if [ -e ${pidfile} ];
    then
        echo "${name} is already running"
    else
        echo "Starting ${name}"
        /usr/sbin/daemon -u ${nzbget_user} -p ${pidfile} ${command} ${command_args}
    fi
}

nzbget_stop()
{
    if [ -e ${pidfile} ];
    then
        echo "Stopping ${name}"
        kill `cat ${pidfile}`;
        sleep 1
    else
        echo "${name} is not running"
    fi
}

run_rc_command "$1"
